// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _123Vendas.Infra.Context;

#nullable disable

namespace _123Vendas.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016013947_MigrationsInicial")]
    partial class MigrationsInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_123Vendas.Infra.DataModels.ItemVendaDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("DescontoPercentual")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("desconto_percentual");

                    b.Property<Guid>("IdProdutoExterno")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_produto_externo");

                    b.Property<Guid>("IdVenda")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_venda");

                    b.Property<string>("ProdutoDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("produto_descricao");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("ValorUnitarioProduto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_unitario_produto");

                    b.HasKey("Id");

                    b.HasIndex("IdVenda");

                    b.ToTable("item_venda", (string)null);
                });

            modelBuilder.Entity("_123Vendas.Infra.DataModels.VendaDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Cancelada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("cancelada");

                    b.Property<DateTime>("DataEfetuacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_efetuacao");

                    b.Property<Guid>("IdClienteExterno")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_cliente_externo");

                    b.Property<Guid>("IdFilialExterna")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_filial_externa");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("NomeFilial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_filial");

                    b.Property<string>("NumeroVenda")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("numero_venda");

                    b.HasKey("Id");

                    b.HasIndex("DataEfetuacao");

                    b.HasIndex("IdClienteExterno");

                    b.HasIndex("IdFilialExterna");

                    b.HasIndex("NumeroVenda");

                    b.ToTable("venda", (string)null);
                });

            modelBuilder.Entity("_123Vendas.Infra.DataModels.ItemVendaDataModel", b =>
                {
                    b.HasOne("_123Vendas.Infra.DataModels.VendaDataModel", "Venda")
                        .WithMany("ItensDaVenda")
                        .HasForeignKey("IdVenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("_123Vendas.Infra.DataModels.VendaDataModel", b =>
                {
                    b.Navigation("ItensDaVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
